### ISSUE TITLE
Purchases: NoSuchElementException

### ISSUE THREAD

**Issue by AndrazP** [RevenueCat/purchases-android#114]
Library version: **3.0.6**

**Stack trace**:
`Fatal Exception: java.util.NoSuchElementException: Collection contains no element matching the predicate.
       at com.revenuecat.purchases.Purchases$postPurchases$$inlined$forEach$lambda$1.invoke(Purchases.java:1324)
       at com.revenuecat.purchases.Purchases$postPurchases$$inlined$forEach$lambda$1.invoke(Purchases.java:49)
       at com.revenuecat.purchases.BillingWrapper$querySkuDetailsAsync$1$1.onSkuDetailsResponse(BillingWrapper.java:139)
       at com.android.billingclient.api.BillingClientImpl$10$1.run(BillingClientImpl.java:784)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)`

This issue has **7** crashes affecting **4** users.
![Screenshot 2020-02-29 at 20 26 48](https://user-images.githubusercontent.com/1963904/75613766-da2b0900-5b31-11ea-9462-cbd8b0c77d92.png)

**Comment by vegaro** [comment]
I have identified the issue and I am working on a fix. Will update here when the fix is released

**Comment by vegaro** [comment]
@AndrazP Just released 3.0.7 that should fix this

**Comment by AndrazP** [comment]
Thank you! We will update it in our next app release.
