### ISSUE TITLE
Support for pending purchases must be enabled. Enable this by calling 'enablePendingPurchases()' on BillingClientBuilder.

### ISSUE THREAD

**Issue by Nyceane** [RevenueCat/purchases-android#137]
Enabling or disabling the android billing class makes absolutely no effect here.

//implementation 'com.android.billingclient:billing:2.1.0'
implementation 'com.revenuecat.purchases:purchases:3.1.0'

I am Simply calling 
```
        Purchases.isFeatureSupported(BillingClient.FeatureType.SUBSCRIPTIONS, context, new Callback<Boolean>() {
            @Override
            public void onReceived(Boolean result) {
                Log.e("foo", "bar");
            }
        });
```

Getting 
```
2020-05-08 18:28:59.623 11561-11561/com.test.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mixpose.android, PID: 11561
    java.lang.IllegalArgumentException: Support for pending purchases must be enabled. Enable this by calling 'enablePendingPurchases()' on BillingClientBuilder.
        at com.android.billingclient.api.BillingClient$Builder.build(BillingClient.java:309)
        at com.revenuecat.purchases.Purchases$Companion.isFeatureSupported(Purchases.kt:1334)
        at com.revenuecat.purchases.Purchases.isFeatureSupported(Purchases.kt)
        at com.test.android.dal.PaymentDAL.IsBillingSupported(PaymentDAL.java:58)
        at com.test.android.fragments.ProductFragment$1.onClick(ProductFragment.java:48)
        at android.view.View.performClick(View.java:5610)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:967)
        at android.view.View$PerformClick.run(View.java:22265)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

**Comment by vegaro** [comment]
Hi! We indeed have a bug, sorry about that. 

I just opened https://github.com/RevenueCat/purchases-android/pull/138 which should fix it. I am not sure when it will be released, but on the meantime, you should be able to achieve the same functionality by copying the static function in one of your classes:

```kotlin
       fun isFeatureSupported(
            @BillingClient.FeatureType feature: String, context: Context,
            callback: Callback<Boolean>
        ) {
            BillingClient.newBuilder(context).enablePendingPurchases().setListener { _, _ -> }
                .build()
                .let { billingClient ->
                    billingClient.startConnection(
                        object : BillingClientStateListener {
                            override fun onBillingSetupFinished(billingResult: BillingResult) {
                                try {
                                    val featureSupported = billingClient.isFeatureSupported(feature)
                                    billingClient.endConnection()
                                    callback.onReceived(featureSupported.responseCode == BillingClient.BillingResponseCode.OK)
                                } catch (e: IllegalArgumentException) {
                                    // Play Services not available
                                    callback.onReceived(false)
                                }
                            }

                            override fun onBillingServiceDisconnected() {
                                try {
                                    billingClient.endConnection()
                                } catch (e: IllegalArgumentException) {
                                } finally {
                                    callback.onReceived(false)
                                }
                            }
                        })
                }
        }
```

**Comment by Nyceane** [comment]
Thanks @vegaro, is it possible to write this in java?  not sure how to do .build().let  in java
