### ISSUE TITLE
TimeoutException at AttributionFetcher.getAdvertisingID 

### ISSUE THREAD

**Issue by AndrazP** [RevenueCat/purchases-android#193]
After updating RevenueCat Android library from 3.3.4 to 3.3.5 we are starting to see the following crash:
```
Fatal Exception: java.lang.Error: java.io.IOException: java.util.concurrent.TimeoutException: Timed out waiting for the service connection
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

Caused by java.io.IOException: java.util.concurrent.TimeoutException: Timed out waiting for the service connection
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(AdvertisingIdClient.java:16)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(AdvertisingIdClient.java:25)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(AdvertisingIdClient.java:47)
       at com.revenuecat.purchases.subscriberattributes.AttributionFetcher.getAdvertisingID(AttributionFetcher.java:34)
       at com.revenuecat.purchases.subscriberattributes.AttributionFetcher.access$getAdvertisingID(AttributionFetcher.java:12)
       at com.revenuecat.purchases.subscriberattributes.AttributionFetcher$getDeviceIdentifiers$1.run(AttributionFetcher.java:21)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

It must be connected with ```Purchases.sharedInstance.collectDeviceIdentifiers()``` that was introduced in latest release. We are calling it from Application:onCreate().

**Comment by vegaro** [comment]
Thanks for opening @AndrazP  I will throw a quick release to fix it

**Comment by AndrazP** [comment]
Hi @vegaro 
We are still seeing this crashes with the latest SDK version 3.5.1.
Could it be you missed a case?

```
Fatal Exception: java.lang.Error: java.io.IOException: java.util.concurrent.TimeoutException: Timed out waiting for the service connection
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1168)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

```
Caused by java.io.IOException: java.util.concurrent.TimeoutException: Timed out waiting for the service connection
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(AdvertisingIdClient.java:16)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(AdvertisingIdClient.java:25)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(AdvertisingIdClient.java:47)
       at com.revenuecat.purchases.subscriberattributes.AttributionFetcher.getAdvertisingID(AttributionFetcher.java:35)
       at com.revenuecat.purchases.subscriberattributes.AttributionFetcher.access$getAdvertisingID(AttributionFetcher.java:13)
       at com.revenuecat.purchases.subscriberattributes.AttributionFetcher$getDeviceIdentifiers$1.run(AttributionFetcher.java:22)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by vegaro** [comment]
My bad. I added a `catch` for a `TimeoutException`. But what's being thrown is a `IOException(TimeoutException())`, so we need to change the catch to IOException instead 🤦 

I will make another release. Sorry about that!

**Comment by AndrazP** [comment]
Any plans when the latest fix will be released?

**Comment by ubuntudroid** [comment]
Looks like this has already been released and can be closed? @vegaro

**Comment by vegaro** [comment]
yes! thanks @ubuntudroid!

**Comment by alonp99** [comment]
@vegaro @AndrazP Any idea why this error is happening in the first place?

**Comment by beylmk** [comment]
@alonp99 we call into google's APIs for this, so unfortunately I don't have a ton of details...

https://developers.google.com/android/reference/com/google/android/gms/ads/identifier/AdvertisingIdClient

Sounds like for some reason the connection to Play Services failed. Let me know if you have further questions!
