### ISSUE TITLE
`SkuDetails#getSubscriptionPeriod` returning empty string 

### ISSUE THREAD

**Issue by archie94** [RevenueCat/purchases-android#229]
**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue.

1. Environment
    1. Platform: Android
    2. SDK version: 4.0.0
    3. OS version: MacOS, Linux
    4. Android Studio version: 4.1
    5. How widespread is the issue. Percentage of devices affected. ~1%

2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
Happening on user devices. Unable to reproduce on my end.

3. Steps to reproduce, with a description of expected vs. actual behavior
```
private fun getPriciestPackage(offerings: Offerings): Package? {
        return offerings.current?.availablePackages?.maxBy {
            it.product.priceAmountMicros / parseDuration(it.product.subscriptionPeriod)
        }
    }

private fun parseDuration(duration: String): Int {
        if (duration.isEmpty()) {
            Timber.e(RuntimeException("Purchase Duration is empty")) // we get this log
            return 0 // this incorrect default value causes the crashlog.
        }
        return try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                parseUsingPeriod(duration)
            } else {
                parseUsingPattern(duration)
            }
        } catch (e: Exception) {
            Timber.e(RuntimeException("Failed for duration $duration"))
            Timber.e(e)
            0
        }
    }

```
How do we handle this empty `subscriptionPeriod`? 

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
```
Fatal Exception: java.lang.ArithmeticException: divide by zero
       at a.b.subscription.implementations.RevenueCatPurchaseHelper.getPriciestPackage(RevenueCatPurchaseHelper.java:181)
       at a.b.subscription.implementations.RevenueCatPurchaseHelper.access$getPriciestPackage(RevenueCatPurchaseHelper.java:38)
       at a.b.subscription.implementations.RevenueCatPurchaseHelper$getSubscriptionPlans$2.invoke(RevenueCatPurchaseHelper.java:125)
       at a.b.subscription.implementations.RevenueCatPurchaseHelper$getSubscriptionPlans$2.invoke(RevenueCatPurchaseHelper.java:38)
       at com.revenuecat.purchases.ListenerConversionsKt$receiveOfferingsListener$1.onReceived(ListenerConversionsKt.java:66)
       at com.revenuecat.purchases.Purchases$getOfferings$2.invoke(Purchases.java:276)
       at com.revenuecat.purchases.Purchases$getOfferings$2.invoke(Purchases.java:85)
       at com.revenuecat.purchases.Purchases.dispatch(Purchases.java:1339)
       at com.revenuecat.purchases.Purchases.getOfferings(Purchases.java:275)
       at com.revenuecat.purchases.ListenerConversionsKt.getOfferingsWith(ListenerConversionsKt.java:103)
       at a.b.subscription.implementations.RevenueCatPurchaseHelper.getSubscriptionPlans(RevenueCatPurchaseHelper.java:120)
       at a.b.subscription.SubscriptionViewModel.fetchPlans(SubscriptionViewModel.java:100)
       at a.b.subscription.SubscriptionViewModel.access$fetchPlans(SubscriptionViewModel.java:46)
       at a.b.subscription.SubscriptionViewModel$refresh$1.invoke(SubscriptionViewModel.java:93)
       at a.b.subscription.SubscriptionViewModel$refresh$1.invoke(SubscriptionViewModel.java:46)
       at a.b.subscription.implementations.RevenueCatStatusHelper$isBillingIssueDetected$2.invoke(RevenueCatStatusHelper.java:97)
       at a.b.subscription.implementations.RevenueCatStatusHelper$isBillingIssueDetected$2.invoke(RevenueCatStatusHelper.java:19)
       at com.revenuecat.purchases.ListenerConversionsKt$receivePurchaserInfoListener$1.onReceived(ListenerConversionsKt.java:79)
       at com.revenuecat.purchases.Purchases$retrievePurchaseInfo$1.invoke(Purchases.java:651)
       at com.revenuecat.purchases.Purchases$retrievePurchaseInfo$1.invoke(Purchases.java:85)
       at com.revenuecat.purchases.Purchases.dispatch(Purchases.java:1339)
       at com.revenuecat.purchases.Purchases.retrievePurchaseInfo(Purchases.java:651)
       at com.revenuecat.purchases.Purchases.getPurchaserInfo(Purchases.java:641)
       at com.revenuecat.purchases.ListenerConversionsKt.getPurchaserInfoWith(ListenerConversionsKt.java:250)
       at a.b.subscription.implementations.RevenueCatStatusHelper.isBillingIssueDetected(RevenueCatStatusHelper.java:94)
       at a.b.subscription.implementations.RevenueCatPurchaseHelper.isBillingIssueDetected(RevenueCatPurchaseHelper.java:196)
       at a.b.subscription.SubscriptionViewModel.refresh(SubscriptionViewModel.java:92)
       at a.b.subscription.SubscriptionViewModel.<init>(SubscriptionViewModel.java:85)
       at a.b.subscription.di.SubscriptionModule$provideVM$1.invoke(SubscriptionModule.java:49)
       at a.b.subscription.di.SubscriptionModule$provideVM$1.invoke(SubscriptionModule.java:25)
       at a.b.util.viewmodel.BaseViewModelFactory.create(BaseViewModelFactory.java:10)
       at a.b.subscription.SubscriptionFragment.getClickableSpan(SubscriptionFragment.java:187)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
       at a.b.subscription.di.SubscriptionModule.provideVM(SubscriptionModule.java:50)
       at a.b.subscription.di.SubscriptionModule_ProvideVMFactory.provideVM(SubscriptionModule_ProvideVMFactory.java:43)
       at a.b.subscription.di.DaggerSubscriptionComponent.getISubscriptionViewModel(DaggerSubscriptionComponent.java:35)
       at a.b.subscription.di.DaggerSubscriptionComponent.injectSubscriptionFragment(DaggerSubscriptionComponent.java:43)
       at a.b.subscription.di.DaggerSubscriptionComponent.inject(DaggerSubscriptionComponent.java:39)
       at a.b.subscription.SubscriptionFragment.onAttach(SubscriptionFragment.java:160)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:2672)
       at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:253)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1168)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```
**Additional context**

**Comment by archie94** [comment]
Hi @vegaro 
Any help here will be appreciated!

**Comment by vegaro** [comment]
Hi @archie94! 

According to the SkuDetails documentation https://developer.android.com/reference/com/android/billingclient/api/SkuDetails#getsubscriptionperiod

> Note: Returned only for subscriptions.

Is it possible you have a package that has a managed product? Maybe a lifetime package? I assume you don't because you would be seeing this more often...

Not sure what's going on here... Being the percentage of devices affected so low, I would say this device has a modified device that could be changing responses from Google or the BillingClient has a bug. We don't really have much control over the SkuDetails class since it's part of the Google library...

I would probably change the implementation of your function to not return 0 and avoid parsing the duration if it's "". Something like:

```
    private fun getPriciestPackage(offerings: Offerings): Package? {
        return offerings.current?.availablePackages?.filter { it.product.subscriptionPeriod?.isNotBlank() }?.maxBy {
            it.product.priceAmountMicros / parseDuration(it.product.subscriptionPeriod)
        }
    }
 ```

**Comment by archie94** [comment]
Understood! Thanks for your response. 

>I would probably change the implementation of your function to not return 0 and avoid parsing the duration if it's "". Something like:

Yes. Will do something similar.
