### ISSUE TITLE
java.lang.SecurityException: Binder invocation to an incorrect interface

### ISSUE THREAD

**Issue by matteinn** [RevenueCat/purchases-android#352]
- [ ] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-android/issues)

**Describe the bug**

This is a crash we are seeing from real users in production, the percentage of affected users is tiny but this is being frequently reported by Crashlytics velocity alerts.

1. Environment
   1. Platform: **Android**
   2. SDK version: **4.3.0**
   3. OS version: **mainly Android 8 (86%), Android 6 (8%), Android 11 (3%), ...**
   4. Android Studio version: **shouldn't matter**
   5. How widespread is the issue. Percentage of devices affected. **1 affected user in a million, roughly 10 occurrences per affected user**
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue **Unknown**
3. Steps to reproduce, with a description of expected vs. actual behavior **Unknown**
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

```
Fatal Exception: java.lang.SecurityException: Binder invocation to an incorrect interface
       at android.os.Parcel.nativeEnforceInterface(Parcel.java)
       at android.os.Parcel.enforceInterface(Parcel.java:469)
       at android.app.ApplicationThreadNative.onTransact(ApplicationThreadNative.java:80)
       at android.os.Binder.transact(Binder.java:387)
       at com.google.android.gms.internal.ads_identifier.zza.transactAndReadException()
       at com.google.android.gms.internal.ads_identifier.zzg.getId()
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.getInfo()
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo()
       at com.revenuecat.purchases.subscriberattributes.AttributionFetcher.getAdvertisingID(AttributionFetcher.kt:38)
       at com.revenuecat.purchases.subscriberattributes.AttributionFetcher.access$getAdvertisingID(AttributionFetcher.kt:16)
       at com.revenuecat.purchases.subscriberattributes.AttributionFetcher$getDeviceIdentifiers$1.run(AttributionFetcher.kt:25)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Additional context**

No more informations but I'm happy to provide additional details you may find useful.

**Comment by beylmk** [comment]
Hi @matteinn, thanks for opening this issue and sorry you're seeing this crash. Unfortunately, this one is tricky for us to reproduce, but it sounds like this might be a proguard-related issue...

Could you try adding the lines from [this stackoverflow answer](https://stackoverflow.com/questions/18646899/proguard-cant-find-referenced-class-com-google-android-gms-r/39701449#39701449) to your proguard rules and see if that fixes things? Sounds like most of those lines could be necessary except perhaps the facebook block. 

If the crash seems to be fixed, we should add those to our proguard consumer-rules. Thanks for bringing this to our attention..

**Comment by vegaro** [comment]
@matteinn Did you have any luck with what @beylmk mentioned? I am going to be closing this since we didn't get any response back but feel free to reach back if you have more info.
