### ISSUE TITLE
Android Billing Client crash when user is identified with logInWith() rather than at Purchases.configure() time

### ISSUE THREAD

**Issue by stephen-mojo** [RevenueCat/purchases-android#381]
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [X] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-android/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. If debug logs are not applicable to this issue, please do not remove step 2 when submitting the issue.

Android Billing Client crash on null pointer when user is identified with logInWith() after log in rather than at Purchases.configure() time at app startup.

1. Environment
   1. Platform: Android
   2. SDK version: 31
   3. OS version: 12
   4. Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 3
   5. How widespread is the issue. Percentage of devices affected. 100%
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
```
D/[Purchases] - DEBUG: ℹ️ Debug logging enabled
D/[Purchases] - DEBUG: ℹ️ SDK Version - 4.5.0
D/[Purchases] - DEBUG: 👤 Initial App User ID - null
D/[Purchases] - DEBUG: 👤 Identifying App User ID: $RCAnonymousID:852e83e595bd4b2c98bc8a0773405a5d
D/[Purchases] - DEBUG: ℹ️ Deleting old synced subscriber attributes that don't belong to $RCAnonymousID:852e83e595bd4b2c98bc8a0773405a5d
D/[Purchases] - DEBUG: ℹ️ App foregrounded
D/[Purchases] - DEBUG: ℹ️ PurchaserInfo cache is stale, updating from network in foreground.
D/[Purchases] - DEBUG: ℹ️ Offerings cache is stale, updating from network in foreground
D/[Purchases] - DEBUG: 😻 Offerings updated from network.
D/[Purchases] - DEBUG: ℹ️ Skipping updating pending purchase queue since BillingClient is not connected yet.
D/[Purchases] - DEBUG: ℹ️ No subscriber attributes to synchronize.
D/[Purchases] - DEBUG: ℹ️ Starting connection for com.android.billingclient.api.BillingClientImpl@3ecf4d1
D/[Purchases] - DEBUG: ℹ️ Billing Service Setup finished for com.android.billingclient.api.BillingClientImpl@3ecf4d1
D/[Purchases] - DEBUG: ℹ️ Updating pending purchase queue
D/[Purchases] - DEBUG: ℹ️ API request started: GET /subscribers/%24RCAnonymousID%3A852e83e595bd4b2c98bc8a0773405a5d
D/[Purchases] - DEBUG: ℹ️ API request completed with status: GET /subscribers/%24RCAnonymousID%3A852e83e595bd4b2c98bc8a0773405a5d 304
D/[Purchases] - DEBUG: ℹ️ API request started: GET /subscribers/%24RCAnonymousID%3A852e83e595bd4b2c98bc8a0773405a5d/offerings
D/[Purchases] - DEBUG: ℹ️ API request completed with status: GET /subscribers/%24RCAnonymousID%3A852e83e595bd4b2c98bc8a0773405a5d/offerings 304
D/[Purchases] - DEBUG: ℹ️ Requesting products from the store with identifiers: sport.mojo.android.subscription.premium.singlesport.yearly, mojo_plus_999_1m_1w0, 4999_1y_1w0
D/[Purchases] - DEBUG: ℹ️ Querying purchases
D/[Purchases] - DEBUG: ℹ️ Cleaning previously sent tokens
D/[Purchases] - DEBUG: ℹ️ Tokens already posted: []
D/[Purchases] - DEBUG: ℹ️ Saving tokens []
D/[Purchases] - DEBUG: ℹ️ Tokens already posted: []
D/[Purchases] - DEBUG: ℹ️ Products request finished for sport.mojo.android.subscription.premium.singlesport.yearly, mojo_plus_999_1m_1w0, mojo_plus_5999_1y_1w0, mojo_plus_499_1m_1w0, mojo_plus_4999_1y_1w0
D/[Purchases] - DEBUG: 💰 Retrieved skuDetailsList: SkuDetails: {"productId":"mojo_plus_4999_1y_1w0","type":"subs","title":"MOJO+ (MOJO Sports)","name":"MOJO+","price":"$49.99","price_amount_micros":49990000,"price_currency_code":"USD","description":"A yearly subscription to MOJO+","subscriptionPeriod":"P1Y","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4JA5oSKZv1_uSfPN5mWujiDNOkvjRgh3Iz0h-Kp91XoYKMysKm84bNz6-hKkzc="}, SkuDetails: {"productId":"mojo_plus_499_1m_1w0","type":"subs","title":"MOJO+ (MOJO Sports)","name":"MOJO+","price":"$4.99","price_amount_micros":4990000,"price_currency_code":"USD","description":"A monthly subscription of MOJO+","subscriptionPeriod":"P1M","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4LijYdLuk4ZOjGDnOQGSn9ITp5Ub6t14PoywmUJ3IvuPzAFMt90fGMMlIXeXgY="}, SkuDetails: {"productId":"mojo_plus_5999_1y_1w0","type":"subs","title":"MOJO+ (MOJO Sports)","name":"MOJO+","price":"$59.99","price_amount_micros":59990000,"price_currency_code":"USD","description":"A yearly subscription to MOJO+","subscriptionPeriod":"P1Y","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4IddM--ZD7Eli-NL-G4WogfmxmsHuj_NPo3jdozSb-QXB6esh16vFXbTVSyaAw="}, SkuDetails: {"productId":"mojo_plus_999_1m_1w0","type":"subs","title":"MOJO+ (MOJO Sports)","name":"MOJO+","price":"$9.99","price_amount_micros":9990000,"price_currency_code":"USD","description":"A monthly subscription to MOJO+","subscriptionPeriod":"P1M","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4JDv7y_R7ciyJrXMrRkt0Qjd6mTG3AQM6xzVUMoQIL5MuHbC6alvjBuyzaXFXc="}, SkuDetails: {"productId":"sport.mojo.android.subscription.premium.singlesport.yearly","type":"subs","title":"MOJO+ Single Sport Yearly (MOJO Sports)","name":"MOJO+ Single Sport Yearly","price":"$19.99","price_amount_micros":19990000,"price_currency_code":"USD","description":"A yearly subscription to MOJO+ Single Sport","subscriptionPeriod":"P1Y","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4KIC_X8s5EZKj825091ZS2qmjjVbSqMtidmU5q1IjHLxiywMPQRPkNyjdy1RLI="}
D/[Purchases] - DEBUG: 💰 mojo_plus_4999_1y_1w0 - SkuDetails: {"productId":"mojo_plus_4999_1y_1w0","type":"subs","title":"MOJO+ (MOJO Sports)","name":"MOJO+","price":"$49.99","price_amount_micros":49990000,"price_currency_code":"USD","description":"A yearly subscription to MOJO+","subscriptionPeriod":"P1Y","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4JA5oSKZv1_uSfPN5mWujiDNOkvjRgh3Iz0h-Kp91XoYKMysKm84bNz6-hKkzc="}
D/[Purchases] - DEBUG: 💰 mojo_plus_499_1m_1w0 - SkuDetails: {"productId":"mojo_plus_499_1m_1w0","type":"subs","title":"MOJO+ (MOJO Sports)","name":"MOJO+","price":"$4.99","price_amount_micros":4990000,"price_currency_code":"USD","description":"A monthly subscription of MOJO+","subscriptionPeriod":"P1M","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4LijYdLuk4ZOjGDnOQGSn9ITp5Ub6t14PoywmUJ3IvuPzAFMt90fGMMlIXeXgY="}
D/[Purchases] - DEBUG: 💰 mojo_plus_5999_1y_1w0 - SkuDetails: {"productId":"mojo_plus_5999_1y_1w0","type":"subs","title":"MOJO+ (MOJO Sports)","name":"MOJO+","price":"$59.99","price_amount_micros":59990000,"price_currency_code":"USD","description":"A yearly subscription to MOJO+","subscriptionPeriod":"P1Y","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4IddM--ZD7Eli-NL-G4WogfmxmsHuj_NPo3jdozSb-QXB6esh16vFXbTVSyaAw="}
D/[Purchases] - DEBUG: 💰 mojo_plus_999_1m_1w0 - SkuDetails: {"productId":"mojo_plus_999_1m_1w0","type":"subs","title":"MOJO+ (MOJO Sports)","name":"MOJO+","price":"$9.99","price_amount_micros":9990000,"price_currency_code":"USD","description":"A monthly subscription to MOJO+","subscriptionPeriod":"P1M","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4JDv7y_R7ciyJrXMrRkt0Qjd6mTG3AQM6xzVUMoQIL5MuHbC6alvjBuyzaXFXc="}
D/[Purchases] - DEBUG: 💰 sport.mojo.android.subscription.premium.singlesport.yearly - SkuDetails: {"productId":"sport.mojo.android.subscription.premium.singlesport.yearly","type":"subs","title":"MOJO+ Single Sport Yearly (MOJO Sports)","name":"MOJO+ Single Sport Yearly","price":"$19.99","price_amount_micros":19990000,"price_currency_code":"USD","description":"A yearly subscription to MOJO+ Single Sport","subscriptionPeriod":"P1Y","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4KIC_X8s5EZKj825091ZS2qmjjVbSqMtidmU5q1IjHLxiywMPQRPkNyjdy1RLI="}
D/[Purchases] - DEBUG: 👤 Logging in from $RCAnonymousID:852e83e595bd4b2c98bc8a0773405a5d -> 3140f2e5-4379-46bb-8f23-4244cf62e960
D/[Purchases] - DEBUG: ℹ️ API request started: POST /subscribers/identify
D/[Purchases] - DEBUG: ℹ️ API request completed with status: POST /subscribers/identify 200
D/[Purchases] - DEBUG: 👤 Logged in successfully as 3140f2e5-4379-46bb-8f23-4244cf62e960. Created: false
D/[Purchases] - DEBUG: ℹ️ Found 0 unsynced attributes for App User ID: $RCAnonymousID:852e83e595bd4b2c98bc8a0773405a5d
D/[Purchases] - DEBUG: ℹ️ Deleting subscriber attributes for $RCAnonymousID:852e83e595bd4b2c98bc8a0773405a5d from cache
D/[Purchases] - DEBUG: ℹ️ API request started: GET /subscribers/3140f2e5-4379-46bb-8f23-4244cf62e960/offerings
D/[Purchases] - DEBUG: ℹ️ API request completed with status: GET /subscribers/3140f2e5-4379-46bb-8f23-4244cf62e960/offerings 200
D/[Purchases] - DEBUG: ℹ️ Requesting products from the store with identifiers: sport.mojo.android.subscription.premium.singlesport.yearly, mojo_plus_999_1m_1w0, mojo_plus_5999_1y_1w0, mojo_plus_499_1m_1w0, mojo_plus_4999_1y_1w0
D/[Purchases] - DEBUG: ℹ️ Products request finished for sport.mojo.android.subscription.premium.singlesport.yearly, mojo_plus_999_1m_1w0, mojo_plus_5999_1y_1w0, mojo_plus_499_1m_1w0, mojo_plus_4999_1y_1w0
D/[Purchases] - DEBUG: 💰 Retrieved skuDetailsList: SkuDetails: {"productId":"mojo_plus_4999_1y_1w0","type":"subs","title":"MOJO+ (MOJO Sports)","name":"MOJO+","price":"$49.99","price_amount_micros":49990000,"price_currency_code":"USD","description":"A yearly subscription to MOJO+","subscriptionPeriod":"P1Y","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4JA5oSKZv1_uSfPN5mWujiDNOkvjRgh3Iz0h-Kp91XoYKMysKm84bNz6-hKkzc="}, SkuDetails: {"productId":"mojo_plus_499_1m_1w0","type":"subs","title":"MOJO+ (MOJO Sports)","name":"MOJO+","price":"$4.99","price_amount_micros":4990000,"price_currency_code":"USD","description":"A monthly subscription of MOJO+","subscriptionPeriod":"P1M","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4LijYdLuk4ZOjGDnOQGSn9ITp5Ub6t14PoywmUJ3IvuPzAFMt90fGMMlIXeXgY="}, SkuDetails: {"productId":"mojo_plus_5999_1y_1w0","type":"subs","title":"MOJO+ (MOJO Sports)","name":"MOJO+","price":"$59.99","price_amount_micros":59990000,"price_currency_code":"USD","description":"A yearly subscription to MOJO+","subscriptionPeriod":"P1Y","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4IddM--ZD7Eli-NL-G4WogfmxmsHuj_NPo3jdozSb-QXB6esh16vFXbTVSyaAw="}, SkuDetails: {"productId":"mojo_plus_999_1m_1w0","type":"subs","title":"MOJO+ (MOJO Sports)","name":"MOJO+","price":"$9.99","price_amount_micros":9990000,"price_currency_code":"USD","description":"A monthly subscription to MOJO+","subscriptionPeriod":"P1M","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4JDv7y_R7ciyJrXMrRkt0Qjd6mTG3AQM6xzVUMoQIL5MuHbC6alvjBuyzaXFXc="}, SkuDetails: {"productId":"sport.mojo.android.subscription.premium.singlesport.yearly","type":"subs","title":"MOJO+ Single Sport Yearly (MOJO Sports)","name":"MOJO+ Single Sport Yearly","price":"$19.99","price_amount_micros":19990000,"price_currency_code":"USD","description":"A yearly subscription to MOJO+ Single Sport","subscriptionPeriod":"P1Y","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4KIC_X8s5EZKj825091ZS2qmjjVbSqMtidmU5q1IjHLxiywMPQRPkNyjdy1RLI="}
D/[Purchases] - DEBUG: 💰 mojo_plus_4999_1y_1w0 - SkuDetails: {"productId":"mojo_plus_4999_1y_1w0","type":"subs","title":"MOJO+ (MOJO Sports)","name":"MOJO+","price":"$49.99","price_amount_micros":49990000,"price_currency_code":"USD","description":"A yearly subscription to MOJO+","subscriptionPeriod":"P1Y","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4JA5oSKZv1_uSfPN5mWujiDNOkvjRgh3Iz0h-Kp91XoYKMysKm84bNz6-hKkzc="}
D/[Purchases] - DEBUG: 💰 mojo_plus_499_1m_1w0 - SkuDetails: {"productId":"mojo_plus_499_1m_1w0","type":"subs","title":"MOJO+ (MOJO Sports)","name":"MOJO+","price":"$4.99","price_amount_micros":4990000,"price_currency_code":"USD","description":"A monthly subscription of MOJO+","subscriptionPeriod":"P1M","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4LijYdLuk4ZOjGDnOQGSn9ITp5Ub6t14PoywmUJ3IvuPzAFMt90fGMMlIXeXgY="}
D/[Purchases] - DEBUG: 💰 mojo_plus_5999_1y_1w0 - SkuDetails: {"productId":"mojo_plus_5999_1y_1w0","type":"subs","title":"MOJO+ (MOJO Sports)","name":"MOJO+","price":"$59.99","price_amount_micros":59990000,"price_currency_code":"USD","description":"A yearly subscription to MOJO+","subscriptionPeriod":"P1Y","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4IddM--ZD7Eli-NL-G4WogfmxmsHuj_NPo3jdozSb-QXB6esh16vFXbTVSyaAw="}
D/[Purchases] - DEBUG: 💰 mojo_plus_999_1m_1w0 - SkuDetails: {"productId":"mojo_plus_999_1m_1w0","type":"subs","title":"MOJO+ (MOJO Sports)","name":"MOJO+","price":"$9.99","price_amount_micros":9990000,"price_currency_code":"USD","description":"A monthly subscription to MOJO+","subscriptionPeriod":"P1M","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4JDv7y_R7ciyJrXMrRkt0Qjd6mTG3AQM6xzVUMoQIL5MuHbC6alvjBuyzaXFXc="}
D/[Purchases] - DEBUG: 💰 sport.mojo.android.subscription.premium.singlesport.yearly - SkuDetails: {"productId":"sport.mojo.android.subscription.premium.singlesport.yearly","type":"subs","title":"MOJO+ Single Sport Yearly (MOJO Sports)","name":"MOJO+ Single Sport Yearly","price":"$19.99","price_amount_micros":19990000,"price_currency_code":"USD","description":"A yearly subscription to MOJO+ Single Sport","subscriptionPeriod":"P1Y","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4KIC_X8s5EZKj825091ZS2qmjjVbSqMtidmU5q1IjHLxiywMPQRPkNyjdy1RLI="}
D/[Purchases] - DEBUG: ℹ️ Vending Offerings from cache
D/[Purchases] - DEBUG: ℹ️ Vending PurchaserInfo from cache.
D/[Purchases] - DEBUG: ℹ️ Checking if cache is stale AppInBackground false
D/[Purchases] - DEBUG: ℹ️ Checking if cache is stale AppInBackground false
D/[Purchases] - DEBUG: 💰 Purchase started - product:  com.revenuecat.purchases.models.ProductDetails@5461adf4  - offering: mojo_plus
D/[Purchases] - DEBUG: 💰 Purchasing product: mojo_plus_5999_1y_1w0
```

3. Steps to reproduce, with a description of expected vs. actual behavior

*Repro Steps:*
- Start the app with the user signed out (no user ID yet).
- Initialize RevenueCat immediately at app startup with in an [Android Startup Initializer](https://developer.android.com/topic/libraries/app-startup) with: `Purchases.configure(context, key, null)`
- Sign a user into my server to get a user ID.
- Immediately log the user into RevenueCat with: `Purchases.sharedInstance.logInWith(userId, ::onError, ::onSuccess)`
- Notice that the user is successfully logged into RevenueCat according to logs.
- Go to my app's paywall screen and load all available packages.
- Click on any package to launch the purchase flow.

*Expected Behavior*
The purchase flow launches.

*Actual Behavior*
App crashes with the following exception:
```
D/UserRepositoryImpl$handleUserToken: Successfully logged in RevenueCat user - Created: false - PurchaserInfo: <PurchaserInfo
     latestExpirationDate: null
    activeSubscriptions:  {},
    activeEntitlements: [],
    entitlements: [],
    nonSubscriptionTransactions: [],
    requestDate: Tue Nov 23 16:05:02 PST 2021
    >
D/PaywallViewModel$getOffers: Successfully fetched RevenueCat offerings:
...
D/[Purchases] - DEBUG: 💰 Purchase started - product:  com.revenuecat.purchases.models.ProductDetails@d6a3780c  - offering: mojo_plus
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sport.mojo.android, PID: 13823
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
        at com.android.billingclient.api.BillingClientImpl.launchBillingFlow(com.android.billingclient:billing@@4.0.0:56)
        at com.revenuecat.purchases.google.BillingWrapper$launchBillingFlow$1.invoke(BillingWrapper.kt:216)
        at com.revenuecat.purchases.google.BillingWrapper$launchBillingFlow$1.invoke(BillingWrapper.kt:51)
        at com.revenuecat.purchases.google.BillingWrapper.withConnectedClient(BillingWrapper.kt:571)
        at com.revenuecat.purchases.google.BillingWrapper.launchBillingFlow(BillingWrapper.kt:215)
        at com.revenuecat.purchases.google.BillingWrapper.access$launchBillingFlow(BillingWrapper.kt:51)
        at com.revenuecat.purchases.google.BillingWrapper$makePurchaseAsync$2.invoke(BillingWrapper.kt:206)
        at com.revenuecat.purchases.google.BillingWrapper$makePurchaseAsync$2.invoke(BillingWrapper.kt:51)
        at com.revenuecat.purchases.google.BillingWrapper$executePendingRequests$1$1$1.run(BillingWrapper.kt:79)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

- I only run into this issue when the user identification is delayed until after login. If the user ID is present at startup, there is no issue. In other words, If I log the user in, kill the app, and restart it, the Android Startup Initializer has a user ID cached so it no longer configures RevenueCat with a null user ID. `Purchases.configure(context, key, cachedUserId)` If I go to the paywall after launching with a user ID, the purchase flows launch just fine with no crash.

- I also downgraded back to 4.2.1 (the last version we were using when I didn't see this crash in the crash reports) and moved back to Purchases.sharedInstance.identifyWith() instead of Purchases.sharedInstance.logInWith() and I am still running into the same issue.

**Comment by stephen-mojo** [comment]
After hours and hours of digging into this, the suspected culprit is not what I expected. It appears that clearing my Activity's Intent might be what is causing it.

My app uses Android Jetpack Navigation for navigating in between Fragments all within a single Activity. There are many instances where I need to reset the entire navigation graph (I can go further into detail on that if you want, but for brevity's sake I will leave the reasoning out for now). Logging in with a new user is one of those instances. When I do so, I also clear the Activity's intent since deep links are re-processed when calling NavController.setGraph(). I don't want a deep link to trigger more than once. 

When I comment out the line that clears the Activity's intent, the issue with the crash disappears. Does RevenueCat somehow leverage the Activity's intent when launching the purchase flow for a package?

MainActivity.kt
```
fun resetGraph() {
        intent = null

        val navHostFragment = supportFragmentManager.findFragmentById(R.id.main_nav_host_fragment_container_view) as NavHostFragment
        navHostFragment.navController.setGraph(R.navigation.nav_graph_main)
    }
```

**Comment by stephen-mojo** [comment]
Looks like this is not a RevenueCat issue, more a Google billing client issue. Seems they assume that the Activity's intent is non-null. Looks like an oversight on their part (unless someone can tell me otherwise.) 

https://stackoverflow.com/questions/65095426/android-play-store-crashes-during-billingclient-launchbillingflow

**Comment by beylmk** [comment]
Hi @stephen-mojo thanks for opening this issue, and for letting us know about your findings. It does look like this is a BillingClient issue, but we can help our users by detecting this case and providing a more detailed response. I've added a ticket to the backlog and will respond back here once our team has worked on it.

**Comment by beylmk** [comment]
> My app uses Android Jetpack Navigation for navigating in between Fragments all within a single Activity. There are many instances where I need to reset the entire navigation graph (I can go further into detail on that if you want, but for brevity's sake I will leave the reasoning out for now). 
> 
> MainActivity.kt
> 
> ```
> fun resetGraph() {
>     intent = null
> ```

Hi @stephen-mojo, if you have time, could you elaborate for us on why you set the intent to null? Was that recommended to you by the Navigation library? Does the intent need to remain null, or is it only used when the activity is launched?

We are thinking of releasing a [fix](https://github.com/RevenueCat/purchases-android/pull/430) that will check if the intent is null before calling `launchBillingFlow`, and set to new Intent() if so, but we want to understand whether there will be any undesirable consequences. The other option is to just surface a warning log, so that if the crash occurs our users at least know why. We'd love your input!
