### ISSUE TITLE
[ANR] Fresh ANR reported from BillingWrapper class

### ISSUE THREAD

**Issue by raghav2945** [RevenueCat/purchases-android#524]
> Hey @raghav2945, excited to say we have the new release out with this fix! Check out 5.0.0: https://github.com/RevenueCat/purchases-android/releases/tag/5.0.0
> 
> _Originally posted by @beylmk in https://github.com/RevenueCat/purchases-android/issues/432#issuecomment-1081268150_

With the new integeration, we start receiving a new ANR. Although it shows the same stack-trace with one method difference I observerd is `startConnectionOnMainThread`, which I can't see in previous reporting. Could you please have a look. Sharing the new stack for reference

```
main (native): tid=1 systid=4371 
#00 pc 0xa0058 libc.so 
#01 pc 0x6c2d3 libc.so 
#02 pc 0x3a2c7 libbinder.so 
#03 pc 0x3b215 libbinder.so 
#04 pc 0x3afdb libbinder.so 
#05 pc 0x356bf libbinder.so 
#06 pc 0xcd5a3 libandroid_runtime.so 
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:605)
       at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6398)
       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1696)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1650)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1638)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:686)
       at com.android.billingclient.api.zzh.zzc(zzh.java:1)
       at com.android.billingclient.api.zzi.zze(zzi.java:32)
       at com.android.billingclient.api.BillingClientImpl.startConnection(BillingClientImpl.java:36)
       at com.revenuecat.purchases.google.BillingWrapper.startConnection(BillingWrapper.java:109)
       at com.revenuecat.purchases.google.BillingWrapper$startConnectionOnMainThread$1.run(BillingWrapper.java:95)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8550)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
```

**Comment by aboedo** [comment]
hi @raghav2945! Thanks for trying out the new version and for reporting this. We'll investigate and try to figure out what's going on.

**Comment by aboedo** [comment]
It looks like there might be instances where Google's `BillingClient.startConnection` simply never finishes, and that's where the connection would entirely fail. 

This is nearly impossible to reproduce artificially, sadly, but we're trying to think about solutions. 

It seems from Google's docs [(or the closest thing to it, sadly)](https://github.com/android/play-billing-samples/blob/8f8792fe23e343883984f361a5ecb56e70653911/TrivialDriveKotlin/app/src/main/java/com/sample/android/trivialdrivesample/billing/BillingDataSource.kt#L156) that this should only happen in fairly rare causes, if the Google Play Store self-upgrades or is force closed. 

Does the volume you're seeing seem to match up with that?

**Comment by aboedo** [comment]
@raghav2945 sounds good, let us know how it goes! Hopefully the volume remains low 🤞
