### ISSUE TITLE
NoSuchElementException AbstractQueue.remove

### ISSUE THREAD

**Issue by thisisthekap** [RevenueCat/purchases-android#526]
We got a `NoSuchElementException` in `BillingWrapper.executePendingRequests`.

I found out, that this exception was fixed in #65. The fix was to synchronize all calls to `serviceRequests`.

Furthermore, I found out that `BillingWrapper.executeRequestOnUIThread´ does not synchronize the access to `serviceRequests` in the way other methods do. So I suggest that 2 different synchronization contexts are in place here, which may lead to the issue described.

I suggest to synchronize the access to `serviceRequests` in `BillingWrapper.executeRequestOnUIThread` as well.

**Stacktrace:**

```
java.util.NoSuchElementException
  at java.util.AbstractQueue.remove(AbstractQueue.java:117)
  at com.revenuecat.purchases.google.BillingWrapper.executePendingRequests(Unknown Source:22)
  at com.revenuecat.purchases.google.BillingWrapper.access$executePendingRequests(Unknown Source)
  at com.revenuecat.purchases.google.BillingWrapper$onBillingSetupFinished$1.run(Unknown Source:64)
  at android.os.Handler.handleCallback(Handler.java:938)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loopOnce(Looper.java:226)
  at android.os.Looper.loop(Looper.java:313)
  at android.app.ActivityThread.main(ActivityThread.java:8680)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Environment**
   1. Platform: Android
   2. SDK version: 5.0.0
   3. OS version: Android 12

**Comment by thisisthekap** [comment]
Hi @aboedo!

Ah, was not aware of the missing empty check. This could definitely be the root cause.

But I still see a potential bug in the synchronization:

This one synchronizes the access by forcing it to the ui thread:

https://github.com/RevenueCat/purchases-android/blob/b3544821525febdfc25eb9359d6c8e0acc6c24f4/feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt#L128-L130

This one does the synchronization by using `BillingWrapper` as lock:

https://github.com/RevenueCat/purchases-android/blob/b3544821525febdfc25eb9359d6c8e0acc6c24f4/feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt#L85-L87

As the two ways of synchronization do not share the same context, non synchronized calls between these two are still possible to my point of view.

**Comment by thisisthekap** [comment]
@aboedo Are you able to provide an ETA for this fix?

**Comment by aboedo** [comment]
@thisisthekap I apologize for the delay in replying, I've been out for a few days and didn't get a chance to dig further. We're digging into it now, though. 

I appreciate your observations about the locking mechanisms. You may be onto something. 

I'm not sure that's the issue, though, since in `executeRequestOnUIThread`, we only access the ui thread when calling `startConnectionOnMainThread`, but the rest of the method is done while using `@Synchronized`, which should lock to the same `BillingWrapper` I believe, so all access to the queue object is done while locking to `BillingWrapper`. 

I'm definitely missing something, though, otherwise a race condition wouldn't possibly happen.

**Comment by thisisthekap** [comment]
@aboedo Any news on this one?

**Comment by aboedo** [comment]
@thisisthekap I'm closing this issue due to inactivity, but feel free to reopen if you're still running into issues!
