### ISSUE TITLE
"enablePendingPurchases" on BillingClientBuilder

### ISSUE THREAD

**Issue by Flaque** [RevenueCat/purchases-android#75]
_Sorry to bother, but came across this bug, I fixed it and I'm leaving it here with the fix so if someone's coming across this from Google they'll find it._

On the newest version of purchases-android, `com.revenuecat.purchases:purchases:2.2.2`, I'm encountering an error on startup that looks like this:

```
2019-07-13 15:26:51.607 28965-28965/tech.econn.quirk E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tech.econn.quirk, PID: 28965
    java.lang.IllegalArgumentException: Support for pending purchases must be enabled. Enable this by calling 'enablePendingPurchases()' on BillingClientBuilder.
        at com.android.billingclient.api.BillingClient$Builder.build(BillingClient.java:309)
        at com.revenuecat.purchases.BillingWrapper$ClientFactory.buildClient(BillingWrapper.kt:42)
        at com.revenuecat.purchases.BillingWrapper$startConnection$1.run(BillingWrapper.kt:66)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:175)
        at android.app.ActivityThread.main(ActivityThread.java:6724)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
```

**Comment by Flaque** [comment]
This was happening because I was forcing a newer version of `com.android.billingclient:billing` in my `build.gradle`.

```gradle
configurations.all {
  resolutionStrategy {
    force 'com.android.billingclient:billing:2.0.2'
    // ... other stuff
  }
}
```

I changed the version to [the older version that purchases-android actually uses](https://github.com/RevenueCat/purchases-android/blob/master/purchases/build.gradle#L28) and that fixed it.

```gradle
configurations.all {
  resolutionStrategy {
    force 'com.android.billingclient:billing:1.2.2'
    // ... other stuff
  }
}
```
